name: weikert_teste_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.4.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  dotenv: ^4.1.0
  mongo_dart: ^0.9.1
  logger: ^1.3.0
  jaguar_jwt: ^3.0.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  objectid: ^2.1.0
  uuid: ^3.0.7
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  injectable_generator: ^2.1.6
  shelf_router_generator: ^1.0.6
  build_runner: ^2.4.4
